name: docker

on:
  push:
    branches:
      - main

env:
  project_name: SharperMe
  app_name: WebApi
  docker_registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  build_docker_file:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Printing Info
        run: echo "USERNAME - ${{ github.actor }}, GITHUB TOKEN - ${{ github.GITHUB_TOKEN }}, REPOSITORY - ${{ github.repository }}"
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checking out Repository
        uses: actions/checkout@v4

      - name: Installing Cosign
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6
        with:
          cosign-release: 'v1.13.1'
          
      - name: Installing Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      
      - name: Log into registry ${{ env.docker_registry }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ github.GITHUB_TOKEN }}

      - name: Extracting Docker Metadata
        id: metadata
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.docker_registry }}/${{ env.image_name }}

      - name: Building & Pushing Docker Image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          file: ./${{ env.project_name }}.${{ env.app_name }}/Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-to:ache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Signing Published Docker Image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.metadata.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}