name: dotnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  application_name: ConsoleApp
  project_name: SharperMe

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Packages
        run: dotnet restore src/${{ env.project_name }}.${{ env.application_name }}/${{ env.project_name }}.${{ env.application_name }}.csproj

      - name: Build
        run: dotnet build src/${{ env.project_name }}.${{ env.application_name }}/${{ env.project_name }}.${{ env.application_name }}.csproj --no-restore

      - name: Test
        run: dotnet test src/${{ env.project_name }}.${{ env.application_name }}.Tests/${{ env.project_name }}.${{ env.application_name }}.Tests.csproj

      - name: Upload to Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.project_name }}.${{ env.application_name }}
          path: src/${{ env.project_name }}.${{ env.application_name }}/bin/Debug/net10.0/${{ env.project_name }}.${{ env.application_name }}.dll

