name: dotnet

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test Message'
        default: 'Default Test Message'
        required: true
        type: string

env:
  application_name: ConsoleApp
  project_name: SharperMe

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Packages
        run: echo "Sending Test Message from Input ${{ inputs.test_input }}"

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore Packages
        run: dotnet restore src/${{ env.project_name }}.${{ env.application_name }}/${{ env.project_name }}.${{ env.application_name }}.csproj

      - name: Build
        run: dotnet build src/${{ env.project_name }}.${{ env.application_name }}/${{ env.project_name }}.${{ env.application_name }}.csproj --no-restore

      - name: Test
        run: dotnet test src/${{ env.project_name }}.${{ env.application_name }}.Tests/${{ env.project_name }}.${{ env.application_name }}.Tests.csproj

      - name: Upload to Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.project_name }}.${{ env.application_name }}
          path: src/${{ env.project_name }}.${{ env.application_name }}/bin/Debug/net10.0/${{ env.project_name }}.${{ env.application_name }}.dll

